### ISSUE TITLE
Proposal for package structure and refactoring

### ISSUE THREAD

**Issue by HealthyPear** [cta-observatory/pyirf#10]
This is an attempt to propose and anticipate how the general structure of the package could look like.

Most of it is already there!

**Code to be removed:**

If needed for current development, it shouldn't be removed immediately, but we could at least move it all into to a separated `plots` folder (see issue #31)

- plotting code (e.g. in `pyirf.scripts.lst_performance`)
- notebooks (there is a `notebooks` folder)

**Package structure:**

- `io`
  - it should contain all input formats - the final one + the temporary ones - see #2
  - we want to provide only one output format, luckily! - see #6 
- `resources`, for example configuration files, perhaps for different analyses settings
- `scripts`, theoretically there should be only one in the end, aka the "tool" to produce the IRFs
- `perf`, could be probably renamed in something more clear and it should contain all the classes to optimize cuts, produce the IRFs (it already the case)

**Notes:**

- part of development is about management of the input and configuration; from the latest release of _ctapipe_ some features are available such as the `ctapipe.core.tool class`; from one side we shouldn't reinvent the wheel, on the other side _pyirf_ is supposed to be an independent tool
- since there should be only 1 input format in the end, perhaps the `io` folder will keep containing only the current `io.py` in which there will be 1 input & 1 output format definition

**Comment by MaxNoe** [comment]
For better testability, it would also be better to disentangle configuration and actually calculating things.

Just one example: in `CutsOptimization`, `compute_weights` could acutally be a free function getting `particle_information` as input instead of the `particle` key and relying on `self.config`. This would make this function much easier to unit test and also remove reliance on the config system from such a low-level function.

**Comment by HealthyPear** [comment]
Further things to do or discuss:

- splitting the main DL3 scripts in e.g.
  - calculate IRFs (maybe even further splitting this in the single IRFs)
  - calculate sensitivity
  - DL3 event list files

**Comment by bregeon** [comment]
> splitting the main DL3 scripts in e.g. 

yes, I was about to suggest that.

**Comment by maxnoe** [comment]
This is largely solved, we have a good, logical project structure I'd say
