### ISSUE TITLE
Sub-optimal cut optimization?

### ISSUE THREAD

**Issue by moralejo** [cta-observatory/pyirf#103]
Sub-optimal cut optimization approach?

https://github.com/cta-observatory/pyirf/blob/0159bfe3067b2d88333a39a7ba96c85a88f34849/examples/calculate_eventdisplay_irfs.py#L148-L157

I am not sure I understood everything, but I get the impression that at least in the 10-event limited region things can be done better than they are done now. In the cut scan the flux for 5-sigma is always calculated, but whenever any of the other two conditions is violated, nan is returned for the sensitivity. Then the best sensitivity among the various cuts can only be one in which you get 5 sigma, and over-fulfill the other conditions. In the few TeV range this means you will always have an optimal set of cuts (and a flux) that makes S = 5 sigma and (in general) N>10 (may be much larger). But it could happen that there is a combination of cuts for which N=10 and S>5 sigma for a lower flux. 
So, when you get n<10 events, the right approach is to calculate the flux that would make exactly 10 events (just  scale by 10/n), and put that (and not nan) in the sensitivity. This may beat the flux sensitivities for other sets of cuts. This may be the reason why Eventdisplay calculation beats pyIRF in the few TeV region.

**Comment by maxnoe** [comment]
This was solved quite some time ago.
