### ISSUE TITLE
5 bins per energy decade ?

### ISSUE THREAD

**Issue by calispac** [cta-observatory/pyirf#114]
Hi all, I was looking at some sensitivity plots from pyirf and I realized that the bin definition can be different from a user to another. For instance, by looking at the figure below I am not convinced that there is 5 bins between 1 TeV and 10 TeV. I fact in this region there seems to be slightly less than 5. 

I looked into this function https://github.com/cta-observatory/pyirf/blob/1f86a6728254394545f2603e9222b033152b6a09/pyirf/binning.py#L43 

And it seems to do the job correctly by having bins spaced by 10^\Delta x with \Delta x = 1/5 = 0.2. Maybe it is my understanding of "5 bins per energy decade" that is wrong. 

Also for sake of comparison (in order to make ratio plots) could we fix the energy bins to e.g. 

```python
bins = np.logspace(-2, 3, 5* 6 + 1) # TeV
array([1.00000000e-02, 1.46779927e-02, 2.15443469e-02, 3.16227766e-02,
       4.64158883e-02, 6.81292069e-02, 1.00000000e-01, 1.46779927e-01,
       2.15443469e-01, 3.16227766e-01, 4.64158883e-01, 6.81292069e-01,
       1.00000000e+00, 1.46779927e+00, 2.15443469e+00, 3.16227766e+00,
       4.64158883e+00, 6.81292069e+00, 1.00000000e+01, 1.46779927e+01,
       2.15443469e+01, 3.16227766e+01, 4.64158883e+01, 6.81292069e+01,
       1.00000000e+02, 1.46779927e+02, 2.15443469e+02, 3.16227766e+02,
       4.64158883e+02, 6.81292069e+02, 1.00000000e+03])
```

![image](https://user-images.githubusercontent.com/23462345/99259884-f3d4c380-281a-11eb-85dc-7aabbebb7bdf.png)

**Comment by maxnoe** [comment]
I am not really understanding your point here.

1) pyirf does not plot sensitivities
2) pyirf allows the user to choose the binning
3) pyirf offers a function that does correctly produce `n_bins_per_decade` like binnings, as you observed.

So what exactly is the issue here for pyirf?

**Comment by vuillaut** [comment]
@calispac Fixing the energy bins would be done in lstchain.

**Comment by calispac** [comment]
@vuillaut Ok thanks. But since everyone uses the "5 bins per energy decade" shouldn't we also fix (no repair but freeze) the bins so that one can have the same bins everywhere ? or at least by default that the bins should be in some range.

**Comment by calispac** [comment]
> pyirf offers a function that does correctly produce n_bins_per_decade like binnings, as you observed.

Well my point is : what is ''5 bins per decade" ? 

PYIRF
```python
>>> bins = 10 ** np.arange(-2, 3, 1 / 5)
>>> bins
array([1.00000000e-02, 1.58489319e-02, 2.51188643e-02, 3.98107171e-02,
       6.30957344e-02, 1.00000000e-01, 1.58489319e-01, 2.51188643e-01,
       3.98107171e-01, 6.30957344e-01, 1.00000000e+00, 1.58489319e+00,
       2.51188643e+00, 3.98107171e+00, 6.30957344e+00, 1.00000000e+01,
       1.58489319e+01, 2.51188643e+01, 3.98107171e+01, 6.30957344e+01,
       1.00000000e+02, 1.58489319e+02, 2.51188643e+02, 3.98107171e+02,
       6.30957344e+02])
```

In my understanding of 5 bins per decade:
```python
>>> bins = np.logspace(-2, 3, 5*6+1)
>>> bins
array([1.00000000e-02, 1.46779927e-02, 2.15443469e-02, 3.16227766e-02,
       4.64158883e-02, 6.81292069e-02, 1.00000000e-01, 1.46779927e-01,
       2.15443469e-01, 3.16227766e-01, 4.64158883e-01, 6.81292069e-01,
       1.00000000e+00, 1.46779927e+00, 2.15443469e+00, 3.16227766e+00,
       4.64158883e+00, 6.81292069e+00, 1.00000000e+01, 1.46779927e+01,
       2.15443469e+01, 3.16227766e+01, 4.64158883e+01, 6.81292069e+01,
       1.00000000e+02, 1.46779927e+02, 2.15443469e+02, 3.16227766e+02,
       4.64158883e+02, 6.81292069e+02, 1.00000000e+03])
```

The two are different

**Comment by maxnoe** [comment]
@calispac you have 6 bins per decade there.

**Comment by calispac** [comment]
yes sorry ! so in the PYIRF calculation there is not the last bin

**Comment by maxnoe** [comment]
1 decade is e.g. the space between 10 GeV and 100 GeV. 5 bins per decade means that this space is divided into 5 bins.

**Comment by HealthyPear** [comment]
yes, because that function works with [numpy.arange](https://numpy.org/doc/stable/reference/generated/numpy.arange.html), which by default stops before the last element

**Comment by maxnoe** [comment]
> yes sorry ! so in the PYIRF calculation there is not the last bin

That's because `np.arange` is non-inclusive for the last border and we inherit this behaviour. We "fix" it by going slightly over in the example, e.g. like so:

```
create_bins_per_decade(10 * u.GeV, 101 * u.TeV, 5)
```

Maybe we it would be better if we put this special casing into the function.

**Comment by maxnoe** [comment]
> yes ok, so we agree that in the plot above (although you are telling me it is not ploted with pyirf) there are <5 bins between 1 TeV and 10 TeV ?

Yes, it looks like 4.8 or something bins per decade. But this is not the fault of pyirf. It is also not just the last bin missing.

**Comment by calispac** [comment]
> Yes, it looks like 4.8 or something bins per decade. But this is not the fault of pyirf. It is also not just the last bin missing.

Ok so I understand it is not the fault of pyIRF. In my opinion if every one uses the same bins width (5 per energy decade), one should fix the bins so that we actually have the same bins everywhere. This could avoid mistakes as in the plot or as the one I did stupidly :D. Also to make a comparison (ratio of sensitivities) it makes life easier. 

However, I understand that one would want to have more flexibility in the choice of the bins.

**Comment by HealthyPear** [comment]
In the current setup, this configuration should be done by the pipeline user and not by `pyirf` (which we built to be a simple library)

**Comment by HealthyPear** [comment]
So it's something that you would explicity setup in the function call inside the script that operated from DL2 to DL3 e.g. in `protopipe` or `cta-lstchain`

**Comment by calispac** [comment]
To me the bins is part of the definition of the sensitivity. For instance, theN_excess >= 10 is part of the sensitivity definition so why not also make it configurable by the user ? 
But ok it is not my choice :)

**Comment by maxnoe** [comment]
>  For instance, theN_excess >= 10 is part of the sensitivity definition so why not also make it configurable by the user ?

It is configurable by the user. Everything is. 

The signature of the `relative_sensitivity` function is:
```
def _relative_sensitivity(
    n_on,
    n_off,
    alpha,
    min_significance=5,
    min_signal_events=10,
    min_excess_over_background=0.05,
    significance_function=li_ma_significance,
):
```

So the defaults are the CTA requirements, but you can change them if you want.

**Comment by HealthyPear** [comment]
It is still your choice, because when you call 

```python
sensitivity = calculate_sensitivity(
        signal_hist, background_hist, alpha=ALPHA
    )

you can specify the otherwise default arguments

min_significance=5
min_signal_events=10
min_excess_over_background=0.05

```

**Comment by calispac** [comment]
ok this looks great ! Let's close this issue.

**Comment by maxnoe** [comment]
@calispac Ok, glad we could clear things up.
