### ISSUE TITLE
gammapy and ogadf_schema not in environment

### ISSUE THREAD

**Issue by jsitarek** [cta-observatory/pyirf#127]
the two packages are needed by test_gadf, however they are not included in environment.yml file

**Comment by HealthyPear** [comment]
hi Julian

we do not use conda right now to install pyirf, only pip

those dependencies are obtained from the dev installation as

pip install '.[all]'

or 

pip install '.[tests]' if you already installed the base package

**Comment by maxnoe** [comment]
The environment is thought for users. It is not a place to specify test depedencies.

As written in the dev documentation, you can use `pip install -e .[all]` to get the dev, test and doc dependencies.
https://cta-observatory.github.io/pyirf/install.html#installing-for-development

**Comment by HealthyPear** [comment]
take a look at the installation instructions if you didn't already
https://cta-observatory.github.io/pyirf/install.html

**Comment by jsitarek** [comment]
thx for quick feedback. I made my install creating conda environment, so for my own copy I just added those 2 packaged to the environment file
still, I would like to understand, if the environment is for non-developers only why does it have  pytest and pytest-cov inside ?
there are also some other packages there (e.g. uproot) that I can see are used only in tests and some others (like awkward) that I cannot find a place where are used (maybe as dependancies only)

**Comment by jsitarek** [comment]
I can do it

**Comment by HealthyPear** [comment]
Fixed in #129
