### ISSUE TITLE
Bugs and wrong behaviours found in protopipe.perf

### ISSUE THREAD

**Issue by HealthyPear** [cta-observatory/pyirf#13]
This is a list of bugs or instances of wrong behaviour that have been spotted in `protopipe.perf` (seed for _pyirf_).
The list provides only links to the original issues / PRs.

- [ ]  cta-observatory/protopipe#63

**Comment by MaxNoe** [comment]
You can transfer issues from one repository to another (on the right panel)

**Comment by HealthyPear** [comment]
Thanks! I will then close this issue.
