### ISSUE TITLE
Missing features

### ISSUE THREAD

**Issue by HealthyPear** [cta-observatory/pyirf#16]
This is a **summary** issue.

The purpose of this list is to group more or less evident missing features that should be present in the package.

Each feature should:
- have its own issue which should be linked here
- be a small, contained problem when possible

===============================

- [x] Telescope multiplicity cut ( #15 )
- [ ] Asymmetric IRFs
   - [ ] Effective area
   - [ ] Energy Dispersion
   - [ ] PSF
   - [ ] Background rate (aka [BKG_3D](https://gamma-astro-data-formats.readthedocs.io/en/latest/irfs/full_enclosure/bkg/index.html#bkg-3d))

**Comment by maxnoe** [comment]
Closing for the same reason as the other meta issues.
