### ISSUE TITLE
Project structure discussion

### ISSUE THREAD

**Issue by MaxNoe** [cta-observatory/pyirf#17]
I think we should discuss a bit about the project structure ahead of the coding sprint.

I think it would be beneficiary to implement actual IRF related components for fine-grained than currently.

So have simple functions for calculating the components / to optimization and other tasks as opposed to the currently used very class heavy structure.

This will make it easier to use for different use cases and ease unit testing. Also interfacing with general optimization / minimization libraries will be easier.

Another point is the in-memory data structures we want to use. This is currently also class based.

I think astropy tables or pandas dataframes might offer advantages here over custom classes and are also more easily intrgrated with different io layers.

**Comment by HealthyPear** [comment]
I opened a similar issue #10 some time ago, maybe we can merge the discussion if you think they intersect
