### ISSUE TITLE
Remove python 2 compatibility leftovers

### ISSUE THREAD

**Issue by MaxNoe** [cta-observatory/pyirf#18]
Currently the code contains several python 2 compatibility elements that are not needed anymore now this only supports python >3.6.

For example inheriting from object:
```
class Foo(object):
    pass

```

**Comment by HealthyPear** [comment]
Do you know any nice tool that would catch these compatibility elements without having to scan the entire package?
Something like when you launch e.g. `pep257` or `black`

**Comment by MaxNoe** [comment]
No, we should just keep it in mind and do the changes when we touch those files

**Comment by MaxNoe** [comment]
Here is an overview I found (not checked it thoroughly though):

https://adamj.eu/tech/2019/03/13/dropping-python-2-support/

**Comment by hugovk** [comment]
https://github.com/asottile/pyupgrade/ is a great tool for this. Please see PR #37.
