### ISSUE TITLE
angular resolution function does not respect units of theta in input

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/pyirf#192]
Due to how astropy tables work, the input is assumed to be degrees.

**Comment by HealthyPear** [comment]
apart from the line

`result["angular_resolution"] = np.nan * u.deg`

which would obviously make for an inconsistent QTable, is there any other buggy line?
I would expect the actual operation of calculating the resolution independent on the quantity unit.

A "democratic" fix could be to modify the function call to provide just the `events[theta]` column with the decorator

`@u.quantity_input(theta=u.deg)`

**Comment by maxnoe** [comment]
It's a combination of setting 
```
result["angular_resolution"] = np.nan * u.deg
```

 and then assigning the result of `angular_distance` which is in rad:
```
    result["angular_resolution"][index] = by_bin["theta"].groups.aggregate(
        lambda x: np.quantile(x, ONE_SIGMA_QUANTILE)
    )

```

to something that is not a `QTable`. `Table` just does not check / convert units.

**Comment by HealthyPear** [comment]
Ah! We are using `Table` inside the function, not `QTable`...

So we could just use `QTable` throughout the whole function and set the special case as

`result["angular_resolution"] = np.nan * table["theta"].unit`

and no need for any `quantity_input`  decorators
