### ISSUE TITLE
EventDisplay root to DL2 hdf/fits converter

### ISSUE THREAD

**Issue by MaxNoe** [cta-observatory/pyirf#2]
As a first step to get nice DL2 data to test this we could start
by writing a conversion tool from the DL2 data Gernot provided to an hdf5 based DL2
format similar to the DL1 format now in ctapipe and/or to the ogadf fits format.

**Comment by HealthyPear** [comment]
Given that the first milestone is to reproduce the current EventDisplay IRFs and that this task will not be a 1-week job, I guess it makes sense.

I think Gernot is already working on the conversion in fits format (at least this it's written on his sub-task in the RedMine wiki page of the IRF WG), so we should make sure to double the work.

**Comment by GernotMaier** [comment]
We have a python FITS exporter using uproot, but a few adjustment needs to be made (as it was developed to be used for VERITAS data). Let me check what the status is and come back to you.

**Comment by HealthyPear** [comment]
Thank you very much!

**Comment by HealthyPear** [comment]
Hi @GernotMaier , do you have any news on this?

The current situation is:
- one of the first steps (#4) would be that of reproducing the on-axis IRFs of EventDisplay
- as far as I know right now we have in place 2 input formats (#5) - from _protopipe_ and _lstchain_ (correct me if I'm wrong @vuillaut) - which are both supposed to be superseded by what will become _ctapipe_'s DL2 format.

So I think that having even only one DL2 EvenDisplay file in FITS format would help us to include the input format to read EventDisplay files.

**Comment by GernotMaier** [comment]
Almost there, sorry about the delay.

Tarek provided me a script and we have to fix some minor issues. Should have the files latest on Monday.

**Comment by GernotMaier** [comment]
FITS files are uploaded to the redmine, see the short documentation here:

https://forge.in2p3.fr/projects/cta_analysis-and-simulations/wiki/Eventdisplay_Prod3b_DL2_Lists#FITS-files

Thanks to @TarekHC for the converter tool.

Let me know if the fits tables are working.

**Comment by HealthyPear** [comment]
Thank you!
I (we)'ll let you know!

**Comment by HealthyPear** [comment]
After a quick scan of the files (I opened `gamma_onSource.S.3HB9-FD_ID0.eff-0-CUT0.fits`) it seems that the info about the g/h and direction is missing.

I could have missed something, but I see

```
Filename: /Users/michele/Applications/ctasoft/tests/pyirf/EventDisplay/DL2/gamma_onSource.S.3HB9-FD_ID0.eff-0-CUT0.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU       7   ()      
  1  EVENTS        1 BinTableHDU     44   2659423R x 9C   [1K, 1K, 1E, 1E, 1E, 1E, 1E, 1E, 1J]   
  2  SIMULATED EVENTS    1 BinTableHDU     21   1R x 3C   [60E, 60E, 60E]
```

and if I select the EVENTS tables I see only these columns

`OBS_ID | EVENT_ID | MC_ALT | MC_AZ | MC_ENERGY | ALT | AZ | ENERGY | MULTIP`

**Comment by TarekHC** [comment]
You can get the reconstructed direction from the 'ALT' and 'AZ' columns (true direction from 'MC_*'). Unless we did a mistake storing those variables, the direction information should be there.

The events added are indeed the ones that survive the gamma/hadron cut (already applied). If you definitely need the g/h parameter, we can probably add it, no @GernotMaier?

**Comment by HealthyPear** [comment]
> You can get the reconstructed direction from the 'ALT' and 'AZ' columns (true direction from 'MC_*'). Unless we did a mistake storing those variables, the direction information should be there.
> 

aaahh, yes sorry my bad!

> The events added are indeed the ones that survive the gamma/hadron cut (already applied). If you definitely need the g/h parameter, we can probably add it, no @GernotMaier?

Following the documentation, the "cut 0" data should not have any cut (meaning either of g/h or direction), "cut 1" only g/h, "cut 2" both

**Comment by TarekHC** [comment]
> Following the documentation, the "cut 0" data should not have any cut (meaning either of g/h or direction), "cut 1" only g/h, "cut 2" both

Oh, I assumed Gernot shared the files with the highest cut levels. We indeed added that functionality in case it was useful. Now it seems it is, so we should probably also add the g/h separation parameter. I'll iterate with @GernotMaier and see if it's trivial.

**Comment by GernotMaier** [comment]
Files are uploaded for all cut levels (indicated by the index 0/1/2).

@TarekHC : there is a second tree in the root files called fEventTreeCuts, the leaf "MVA" contains the g/h separation parameter. Note that fEventTreeCuts has exactly the same number of events as the data tree you've used, so mapping the entries in both trees should be simple.

MVA is defined in the interval [-1, 1].

**Comment by GernotMaier** [comment]
Updated FITS files with the g/h separation parameter can be found here:

https://desycloud.desy.de/index.php/s/DzF7EYc9icbdQGo
(please wait a little until all files are uploaded; just want to write this before leaving)

**Comment by HealthyPear** [comment]
I think the purpose of this issue has been fulfilled, am I right?

I am adding all the important URLs to the documentation in the form of a tutorial for the upcoming coding sprint.

If this is sufficient for you I would close this issue.

**Comment by MaxNoe** [comment]
@GernotMaier I just downloaded the `LaPalma_20deg-Cut0.tar.gz` and had a look.

It seems the primary hdu has the wrong TELESCOP:

```
TELESCOP= 'CTA-S.3HB9-FD'      / Telescope and array codename.      
```

the other hdus seem to have the right ones.

**Comment by MaxNoe** [comment]
@GernotMaier also, is there info about the CORSIKA simulated events besides the energy histogram in the second HDU?

A table of the runs with number of showers, spectral index, minimum / maximum energy, viewcone, max impact?

**Comment by GernotMaier** [comment]
@TarekHC - can you help Max with above points?

**Comment by TarekHC** [comment]
Sure, I would be happy to help. 
* The HDU fix is trivial.
* @GernotMaier if you identify the location within your ROOT files of those parameters, I can include them to the table easily

**Comment by GernotMaier** [comment]
There are stored in an object with the name "VMonteCarloRunHeader".

Easiest way is probably to use the Eventdisplay tool *$EVNDISPSYS/bin/printRunParameter* to print them to the screen and the grab them:

```
$EVNDISPSYS/bin/printRunParameter gamma_cone.S.BL-0LSTs15MSTs50SSTs-MSTN_ID0.eff-3.root

Monte Carlo run header
======================
run number: 6140
code version: shower prog 1 (7710), detector prog 1 (1593349643), convert 0
date: 0	0
number of showers: 50000 (each shower used 20 times)
Primary 0
Energy range: [0.003, 330] TeV, powerlaw index -2
Core scattering: 0	2500 [m] (circular)
Azimuth range: [4.57654e-06, 4.57654e-06]
Zenith range: [20, 20]
Viewcone: [0, 10] (1)
Observatory height 2147 [m]
B-Field: 22.586 microT (-24.5021,-4.533)
Atmospheric model: 99
Cherenkov photon wavelength range: [240, 1000]
CORSIKA interaction detail: lowE 0, highE 303, interaction models: lowE 2, highE 3, transition energy 0 GeV
CORSIKA iact options: 187
CERENKOV 1
IACT 1
CEFFIC 0
ATMEXT 1
ATMEXT with refraction 1
VOLUMEDET 1
CURVED 0
SLANT 0
```

**Comment by MaxNoe** [comment]
For future reference, the conversion tool is here: https://github.com/Eventdisplay/Converters/

**Comment by MaxNoe** [comment]
WIth the still experimental uproot 4 it's as easy as:

```

In [1]: import uproot4

In [2]: f = uproot4.open('./gamma_cone.Nb.3AL4-BN15-TI_ID0.eff-0.root')

In [3]: run_header = f['MC_runheader']

In [4]: run_header.all_members
Out[4]: 
{'@fUniqueID': 0,
 '@fBits': 50331648,
 'fName': 'MC_runheader',
 'fTitle': '',
 'runnumber': 12602,
 'shower_prog_id': 1,
 'shower_prog_vers': 6990,
 'detector_prog_id': 1,
 'detector_prog_vers': 1481293431,
 'converter_prog_vers': 0,
 'shower_date': 0,
 'detector_date': 0,
 'primary_id': 0,
 'obsheight': 2147.0,
 'num_showers': 25000,
 'num_use': 20,
 'core_pos_mode': 1,
 'core_range': array([   0., 1900.]),
 'az_range': array([0., 0.]),
 'alt_range': array([1.22173047, 1.22173047]),
 'diffuse': 1,
 'viewcone': array([ 0., 10.]),
 'E_range': array([3.00000003e-03, 3.30000000e+02]),
 'spectral_index': -2.0,
 'B_total': 38.7280158996582,
 'B_inclination': 0.662263810634613,
 'B_declination': 0.0,
 'injection_height': -1.0,
 'fixed_int_depth': 0.0,
 'atmosphere': 36,
 'corsika_iact_options': 187,
 'corsika_low_E_model': 2,
 'corsika_high_E_model': 3,
 'corsika_bunchsize': 5.0,
 'corsika_wlen_min': 240.0,
 'corsika_wlen_max': 700.0,
 'corsika_low_E_detail': 0,
 'corsika_high_E_detail': 101,
 'corsika_low_high_E': 0.0,
 'detector_Simulator': 'NOSET',
 'combined_runHeader': False,
 'fFADC_hilo_multipler': -999.0}
```

But with uproot 3, current stable, there seems to be a problem with underscores:

```
In [6]: f = uproot.open('./gamma_cone.Nb.3AL4-BN15-TI_ID0.eff-0.root')

In [7]: run_header = f['MC_runheader']

In [8]: run_header._fields
Out[8]: 
['runnumber',
 'shower_5f_prog_5f_id',
 'shower_5f_prog_5f_vers',
 'detector_5f_prog_5f_id',
 'detector_5f_prog_5f_vers',
 'converter_5f_prog_5f_vers',
 'shower_5f_date',
 'detector_5f_date',
 'primary_5f_id',
 'obsheight',
 'num_5f_showers',
 'num_5f_use',
 'core_5f_pos_5f_mode',
 'core_5f_range',
 'az_5f_range',
 'alt_5f_range',
 'diffuse',
 'viewcone',
 'E_5f_range',
 'spectral_5f_index',
 'B_5f_total',
 'B_5f_inclination',
 'B_5f_declination',
 'injection_5f_height',
 'fixed_5f_int_5f_depth',
 'atmosphere',
 'corsika_5f_iact_5f_options',
 'corsika_5f_low_5f_E_5f_model',
 'corsika_5f_high_5f_E_5f_model',
 'corsika_5f_bunchsize',
 'corsika_5f_wlen_5f_min',
 'corsika_5f_wlen_5f_max',
 'corsika_5f_low_5f_E_5f_detail',
 'corsika_5f_high_5f_E_5f_detail',
 'corsika_5f_low_5f_high_5f_E',
 'detector_5f_Simulator',
 'combined_5f_runHeader',
 'fFADC_5f_hilo_5f_multipler']

In [9]: {k.replace('_5f_', '_'): getattr(run_header, '_' + k) for k in run_header._fields}
Out[9]: 
{'runnumber': 12602,
 'shower_prog_id': 1,
 'shower_prog_vers': 6990,
 'detector_prog_id': 1,
 'detector_prog_vers': 1481293431,
 'converter_prog_vers': 0,
 'shower_date': 0,
 'detector_date': 0,
 'primary_id': 0,
 'obsheight': 2147.0,
 'num_showers': 25000,
 'num_use': 20,
 'core_pos_mode': 1,
 'core_range': array([   0., 1900.]),
 'az_range': array([0., 0.]),
 'alt_range': array([1.22173047, 1.22173047]),
 'diffuse': 1,
 'viewcone': array([ 0., 10.]),
 'E_range': array([3.00000003e-03, 3.30000000e+02]),
 'spectral_index': -2.0,
 'B_total': 38.7280158996582,
 'B_inclination': 0.662263810634613,
 'B_declination': 0.0,
 'injection_height': -1.0,
 'fixed_int_depth': 0.0,
 'atmosphere': 36,
 'corsika_iact_options': 187,
 'corsika_low_E_model': 2,
 'corsika_high_E_model': 3,
 'corsika_bunchsize': 5.0,
 'corsika_wlen_min': 240.0,
 'corsika_wlen_max': 700.0,
 'corsika_low_E_detail': 0,
 'corsika_high_E_detail': 101,
 'corsika_low_high_E': 0.0,
 'detector_Simulator': b'NOSET',
 'combined_runHeader': False,
 'fFADC_hilo_multipler': -999.0}

In [10]: 
```
