### ISSUE TITLE
Update gammapy

### ISSUE THREAD

**Issue by MaxNoe** [cta-observatory/pyirf#20]
gammapy 0.8 is quite ancient, current release is 0.17 which should be the last before the long-term 1.0

**Comment by HealthyPear** [comment]
yep! @vuillaut is already working on this

**Comment by vuillaut** [comment]
It's the most urgent issue.
Unfortunately, I have had so little time to work on this... 😬

**Comment by vuillaut** [comment]
Anyone with time and willing to work on that is welcome though, I have been too slow.

**Comment by vuillaut** [comment]
Will try to finish that or at least push the minimum before the coding sprint 🙏

**Comment by adonath** [comment]
@vuillaut From a quick look the required changes to update to Gammapy 0.17 are the following:

Basically renaming :
- `cosmic_ray_flux` -> `create_cosmic_ray_spectral_model`
- `CrabSpectrum` -> `create_crab_spectral_model`
- `BinnedDataAxis` & `EnergyBounds` -> `MapAxis`
- `significance_on_off` -> `WStatCountsStatistics`

The only a bit more tricky thing is the `SensitvityEstimator`, which was refactored to work with a `SpectrumDatasetOnOff`, however you can probably get rid of the `Irf` and `BkgData` container classes. Here is a tutorial to show how it's used now: https://docs.gammapy.org/0.17/notebooks/cta_sensitivity.html 

Let us know (slack or here) if you need any help with the transition...

**Comment by HealthyPear** [comment]
I just want to let you know that the current code in PR #12 didn't require updating _gammapy_, so for the usage of that version of _pyirf_ it is not urgent.
Of course, if people from other sub-task groups start playing with the code by using newer code from _gammapy_ this will be required.

**Comment by MaxNoe** [comment]
The point is we should use the current version of gammapy, not some ancient version.

So we should update in any case, not just because we require some new feature of the current gammapy version.

**Comment by MaxNoe** [comment]
Fixen in #36
