### ISSUE TITLE
password for private data

### ISSUE THREAD

**Issue by gear8mike** [cta-observatory/pyirf#201]
How can I get a password for this script:
`./download_private_data.sh`?

**Comment by StFroese** [comment]
Documentation says `The download is password protected, please ask one of the maintainers for the password.` Check the mailmap and write Max maybe

**Comment by maxnoe** [comment]
@gear8mike Please not the we don't use these data anymore for the automated unit tests. These are quite old prod5b DL2 files produced using event display. If you'd like access to newer data like this, I'd suggest contacting Gernot Maier

**Comment by gear8mike** [comment]
@maxnoe so it means that this test example "Calculating Sensitivity and IRFs for EventDisplay DL2 data" from docs is not working anymore? or it requires newer data?
