### ISSUE TITLE
Sphinx search box function not really working

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/pyirf#216]
Reported by @Tobychev via slack: searching for "cuts" or "cut" or even the exact method name "calculate_percentile_cuts" does not turn up any results in the sphinx docs

**Comment by HealthyPear** [comment]
This is weird. Usually you don't need any specific configuration to make this work.

I saw that we are using sphinx 6 from the CI and in the original repository I couldn't find any open or recently closed issue about this.

**Comment by maxnoe** [comment]
This got fixed somewhen, working now
