### ISSUE TITLE
Codacy no longer woking

### ISSUE THREAD

**Issue by RuneDominik** [cta-observatory/pyirf#222]
After the `master` - > `main` change codacy seems to be broken. At least when looking at #221 latest codacy run, there is a `It seems like the branch main is not being analyzed. To review this pull request enable the branch in the repository settings.` warning and the codacy steps are failing. This is probably something someone with codacy access for `pyirf` has to update.

**Comment by maxnoe** [comment]
I didn't set this up. @HealthyPear @kosack, did one of you do this and might you be able to check?

**Comment by maxnoe** [comment]
Edit: okay, was able to login and change the default branch settings. Should work now

**Comment by RuneDominik** [comment]
Yes, this seems to have resolved it, thanks. At least the README-Badge is now displayed correct (again). As for #221 we will see when there is a actual change but it should work as well.
