### ISSUE TITLE
Nearest Simplex finding in ParametrizedNearestSimplexExtrapolator not working

### ISSUE THREAD

**Issue by RuneDominik** [cta-observatory/pyirf#238]
Apparently, `scipy.spatial.Delaunay.plane_distance` does not work in all cases to find the nearest simplex to some point outside the grid's convex hull. For non-rectangular grids this does somewhat work
![non_rect_scipy](https://github.com/cta-observatory/pyirf/assets/22680504/3202575a-baf4-4c8b-9e98-171e7d4f8cf9)
but it fails completely for rectangular grids
![rect_scipy](https://github.com/cta-observatory/pyirf/assets/22680504/816f6c2e-8ed1-49b0-8833-7bb169c1b338)

With some assumptions the problem can be solved geometrically to behave as expected:
![non_rect_geom](https://github.com/cta-observatory/pyirf/assets/22680504/da4775ee-f627-4178-b993-3d36a234c2b2)
![rect_geom](https://github.com/cta-observatory/pyirf/assets/22680504/61504474-a3fd-445f-972d-22badc59ebd4)

I'll create a PR implementing the solution used to create above plots, some of these functions could even be reused for later extrapolation methods (namely blending over visible edges). I'd like, however, some advise where to put the functions used for this as they are quite general. The first place I have in mind would ofc be just as free functions inside `pyirf.interpolation.nearest_simplex_extrapolator` as they are first needed there, but since they are so general and can partially be reused later, maybe we want something as `pyirf.interpolation.utils` @maxnoe?

As of now, the `ParametrizedNearestSimplexExtrapolator` should not be used. As the same approach was used in #237 this issue also blocks this PR.

**Comment by Tobychev** [comment]
From your text it sound like your figures shows the area where you are closest to one of the black points, but I really don't see how the colouring you include shows that, so I'm probably misunderstanding something here. I'd appreciate if you could explain the plots :)

**Comment by RuneDominik** [comment]
Sorry, I was a bit hand-wavy there. The plots show for each point the closest simplex (in this 2D-case triangles) in the Delaunay-triangulation of the points in the plot. I've included the triangulation in the plots below below. We need the closes simplex, as in 2D we are inter-/extrapolating inside/from those.

![non_rect_geom](https://github.com/cta-observatory/pyirf/assets/22680504/3915a0df-4b40-4e75-b9f6-84f6d6777967)
![rect_geom](https://github.com/cta-observatory/pyirf/assets/22680504/40ccf0d8-dddb-4a98-98c9-0dd57d6cf894)
