### ISSUE TITLE
Integration tests

### ISSUE THREAD

**Issue by HealthyPear** [cta-observatory/pyirf#24]
This is probably the most urgent test to add for the coding sprint.

The test should check that the script (which after PR #12 is called make_DL3.py) is able to reach the end of the process and that the files are not empty.
This is basically what I do in `protopipe.scripts.tests` (actually, there the master branch is now outdated, but basically it does this).

It's not much but it would be already something useful to make automatize the development process.

Unfortunately, it is a test that requires test data to run the script on.
The Event Display datafiles I used are too heavy :

- 17M	electron_onSource.S.3HB9-FD_ID0.eff-0-CUT0.fits
- 122M	gamma_onSource.S.3HB9-FD_ID0.eff-0-CUT0.fits
- 123M	proton_onSource.S.3HB9-FD_ID0.eff-0-CUT0.fits

I don't know if there is a tool to extract a "sub"-FITS file from a bigger one or if we can have smaller datasets from EventDisplay.

**Comment by MaxNoe** [comment]
Nitpick: This is not a unit test. A unit test tests a small **unit**.

Your are describing an integration test of the full system.

**Comment by HealthyPear** [comment]
Ah thanks, I didn't know the name, so I put unit in quotes...

**Comment by MaxNoe** [comment]
> I don't know if there is a tool to extract a "sub"-FITS file from a bigger one or if we can have smaller datasets from EventDisplay.

We can just create a smaller, sampled version of these files with a couple of thousand events.

This won't be able to calculate IRFs with small uncertainties in small bins but it could be used to test the chain with large bins.

**Comment by MaxNoe** [comment]
Where are these files now and how can they be accessed? We could also provide a download script and and download them on travis using travis' credential system to provide a password if one is needed.

**Comment by HealthyPear** [comment]
The URLs are linked in Issue #2 (bottom).

I put these URLs also in the usage/tutorial page in the new docs coming with PR #12 .

Regarding Travis doesn't each build have a storage limit? Do you mean the test files?

**Comment by MaxNoe** [comment]
> Regarding Travis doesn't each build have a storage limit? Do you mean the test files?

Yes, but its several tens of GB: https://docs.travis-ci.com/user/reference/overview/

**Comment by HealthyPear** [comment]
Ah ok then probably it's not a problem

Also the computing time right now it is relatively fast

**Comment by MaxNoe** [comment]
> Also the computing time right now it is relatively fast

This also hugely depends on the parameter space for the cut optimization and the number of bins, which can both be kept much smaller for units tests than required for the actual IRFs.

**Comment by HealthyPear** [comment]
Yes, this test should cover the easiest case scenario to catch e.g. horrible crashes that would break the whole thing

**Comment by HealthyPear** [comment]
# What is still missing / to decide

- [ ] where to store test data
- [ ] what test data to store
- [ ] a suite of integration tests (or better a template structure to start)

# Updates

## Storage

Literally anything we can access via a URL from Travis.
If in common with _ctapipe/protopipe/cta-benchmarks_ even better.

## Data

DL2 files possibly without any high-level cut, from any / each of the pipelines to support - notably,
- _Eventdisplay_
- _ctapipe_
- _CTA-MARS_

The size of these files has been discussed briefly above, but essentially small enough to execute the tests in a reasonable time but not too much to inhibit the calculations due to too few events per bin.

## Structure

After PR #36 _pyirf_ will look more like a library (similar to _ctapipe_) with respect to the current master implementation which is based on the main script.

Any pipeline-specific implementation will be stored as example scripts in the `./examples` folder.

There could be **1 template script**, essentially a wrapper for the integration test to interface with each of the example scripts.

This template should:
1. access the test data from Travis CI
2. launch the pipeline-specific example script
3. assert that
    3a. the full DL2 ---> DL3 pipeline section does not crash
    3b. assert that the output file(s) correspond to the format we wish to deliver

**Comment by bregeon** [comment]
we can certainly put the data on `cccta-dataserver` at cc-in2p3.
As, that is an opened http server that we also had planned to use for `ctapipe` and `cta-benchmarks` but I never had time to really make the proper interface.
Still we can make it simple to start with here.

**Comment by MaxNoe** [comment]
The question is, if we can just publish the data, if we need to password protect it and if we need to password protect it. 
I guess this data is not strictly open, but the desy cloud link for the fits files were.

@GernotMaier

**Comment by GernotMaier** [comment]
Definitely not public, more undefined (which is equivalent to not public).

The desy cloud link will decay soon (not password protected doesn’t mean open).

**Comment by bregeon** [comment]
Here as well, I have just launched the discussion with CTAC management and CTAO on how we shall handle these data floating around with undefined status, main points are the following:
1. acknowledge that some data need to be easily available for InT 
2. decide if it's a problem that these data are downloadable by anyone with a good link (or if they shall always be password protected)
3. understand if these data shall be made public, i.e. with minimal documentation for outside CTA
4. agree on how to best serve these data, if possible from a unique access point 

Mean while, I'll copy these data on "my" dedicated server with no password (and I'll also try organize things a bit for ctapipe as well).

**Comment by HealthyPear** [comment]
Ok, it seems that after PR #96 this issue has been now reduced to:

- missing test data (at least #54 )
- test data storage

The second point I am sure will trigger a more detailed discussion on multiple channels so that discussion shouldn't continue here (at least, not in this specific issue - maybe I can open one for future updates?)

For the time being, I will close this issue.
