### ISSUE TITLE
binning.create_histogram_table side effects

### ISSUE THREAD

**Issue by kosack** [cta-observatory/pyirf#259]
`binning.create_histogram_table` "magically" uses a "weight" column if it finds it. This is undocumented and not at all obvious.  It would be better to add another parameter`weight_key="weight"` and mention in the docs that the histogram will be weighted by the column specified by`weight_key`.

The docstring also doesn't mention that it outputs more than just the histogram, but both the normal and weighted version.  And even more unexpected, if it finds a `particle_type` column, it makes grouped histograms by particle type that also end up in the output.  It would be better (and more clear) to add this also as a parameter `group_key="particle_type"` to make it more obvious

**Comment by kosack** [comment]
Just to note this caused a large bug in my test script. I had use the column name "weights" instead of  "weight", but create_histogram_table just silently created a "n_weighted" column with no weights in that case.  It took me a while to find out why the weighted and un-weigted events were identical. 

So additionally, if there is a `weight_key` option, it should fail if that column doesn't exist

**Comment by maxnoe** [comment]
These are good suggestions, and I'll implement them.

https://pyirf.readthedocs.io/en/latest/introduction.html#dl2-event-lists

**Comment by kosack** [comment]
The intro does help (I had missed it!), but I still think hidden assumptions should be more explicit. I had the same issue with some of the other API functions.  Having keywords for the column name helps a lot to understand what is happening underneath.  The defaults can match the introduction, but allowing a user to use an API function without having to remap columns is also nice, especially as it allows for easier comparisons between reconstructors for example.

**Comment by maxnoe** [comment]
yes, agreed
