### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by HealthyPear** [cta-observatory/pyirf#27]
A list currently hard-coded inputs or other future things to make configurable.
Please, open a separate issue for each and link here,

- [ ] particle models ( )
- [ ] theta2 values in optimization mode ( )

**Comment by MaxNoe** [comment]
As  discussed in the other issues about project structure and during the pre-sprint refactoring, we don't want to provide a monolithical tool with lots of configutation options but a library of composable functions.
