### ISSUE TITLE
Astropy 6.0.0 and moved astropy.coordinates.angle_utilities

### ISSUE THREAD

**Issue by RuneDominik** [cta-observatory/pyirf#270]
With the astropy 6.0.0 release the `astropy.coordinates` module was consolidated in [#15220](https://github.com/astropy/astropy/pull/15220) and thus astropy.coordinates.angle_utilities no longer exists, resulting in failing CI jobs (e.g #253). According to astropy's PR this should be an easy fix by simply importing from astropy.coordinates which should even be backwards compatible at least to astropy v5. 

As we currently require `astropy>=4.0.2` we could however think of either fixing and/or updating the version to maintain comparability with other cta-observatory packages.

**Comment by maxnoe** [comment]
Same change done in ctapipe: https://github.com/cta-observatory/ctapipe/pull/2475
