### ISSUE TITLE
Astropy tables VS pandas

### ISSUE THREAD

**Issue by HealthyPear** [cta-observatory/pyirf#28]
Probably it's better to choose only one of them throughout the whole code.
Thanks to @MaxNoe for having pointed out the following information.

**In case we choose Astropy tables**
- they better support units, but are generally not as powerful when it comes to statistics and other manipulation,
- tables support ND rows, pandas cannot handle this.

**In case we choose Pandas:**

If using pandas from FITS data, in order to solve the following error
```python
ValueError: Big-endian buffer not supported on little-endian compiler
```
it is needed to convert to native byte order like [here](https://github.com/fact-project/pyfact/blob/65201e6aa029264b0b4305c6bc8731b3a11b79cc/fact/io.py#L127)

**Comment by bregeon** [comment]
Just wandering if there is any impact from this choice on writing the output to file?
do we just write numpy arrays?

**Comment by MaxNoe** [comment]
This has no impact on writing output, as the file format (fits) is independent from the in memeory representation.

**Comment by vuillaut** [comment]
astropy tables seems the right  choice here, we will have to handle units anyway and will need to have astropy as a dependency.

**Comment by MaxNoe** [comment]
We decided to go for astropy tables (probably QTable).
