### ISSUE TITLE
astropy 6.0 API change

### ISSUE THREAD

**Issue by ccossou** [cta-observatory/pyirf#280]
Hi, 
I've installed pyirf on python 3.10 today, using 
```
pip install pyirf
```
and I got this error
```
ModuleNotFoundError: No module named 'astropy.coordinates.angle_utilities'
```
See this issue in astropy for reference: https://github.com/astropy/astropy/issues/14675
From astropy changelog, they say: 
Removed deprecated angle parsing and formatting utilities from angle_utilities. Use the functions from angle_formats instead. [[#14675](https://github.com/astropy/astropy/issues/14675)]

Either a forced version of astropy in the dependencies, or a change in the import could solve this. 

Hope it helps, 
Christophe

**Comment by maxnoe** [comment]
This is already fixed in the current main branch, I will make a new release soon: https://github.com/cta-observatory/pyirf/pull/271

**Comment by Tobychev** [comment]
@maxnoe Could you do a point release soon please? Can't run the real tests of the irf-tool on the CI with the 10.1 `pyirf` release.
