### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by HealthyPear** [cta-observatory/pyirf#3]
This is a **summary issue**.

The following a list of things that should be started to aid/foster development and usage.
Please, open/work on separate issues and link them here.

- [x]  Continuous integration (CI)
- [x] Unit-tests
- [ ] Test data
   - [ ] Diffuse gamma test data (#54)
   - [ ] Smaller test data set for unit tests (#55)
- [x] Integration tests (#24)
- [x] Documentation
- [x] Benchmarks (#36)
- [x] Continuous deplyoment (CD)
  - [x] #42 
  - [x] update Travis configuration file

In the future, depending on the complexity of this software, this summary issue could become a project by itself.

**Comment by maxnoe** [comment]
I am closing this. We should use labeling to group issues, not master issues that stay open forever.

**Comment by HealthyPear** [comment]
we didn't finish this, we are still missing the diffuse test data

what 's wrong with issue? it is a summary of what is needed with link to the corresponding issues

**Comment by maxnoe** [comment]
Like I said, I think we should use the proper feature of github to group tests: labels.

So instead of an issue Named Maintenance, that is just a list of other issues, we have a label maintenance and github can aautomatically show us all issues with label maintenance.
