### ISSUE TITLE
EventDisplay comparison notebook is included twice

### ISSUE THREAD

**Issue by MaxNoe** [cta-observatory/pyirf#33]
It is in `docs/contributing` (where it does not make sense I think) and the `notebooks` directory

**Comment by HealthyPear** [comment]
usually I do this so the one in notebooks is an empty one to edit, while the one in the docs is a static copy with the latest results

**Comment by MaxNoe** [comment]
That's not good! This just duplicates it and makes it hard to maintain. There are better ways to do this.

Like in ctapipe, where the notebooks are included empty in the repository and are executed during the docs build so the output is included in the docs.

**Comment by HealthyPear** [comment]
I know, but since that is done by the CI pipeline there should be test data stored somewhere, which is not the case now, so that is why I didn't do it

**Comment by MaxNoe** [comment]
Fixed #36
