### ISSUE TITLE
EventDisplay notebook contains hard coded paths to specific user's directories

### ISSUE THREAD

**Issue by MaxNoe** [cta-observatory/pyirf#34]
The notebook is not usable by anyone else because it contains hard coded, absolute paths to data files.

These should be replaced by something that all users can have, e.g. by using a relative path that user's can create a symlink to or by using an env variable

**Comment by HealthyPear** [comment]
Yes, I forgot to clean the indir path.

Anyhow, we do not provide the data with the software, so the user downloads the data and modifies that line (I have to do a tutorial at the beggining of the sprint anway)
