### ISSUE TITLE
Use ogadf-schema to check if output is compliant to gadf

### ISSUE THREAD

**Issue by MaxNoe** [cta-observatory/pyirf#43]
https://github.com/open-gamma-ray-astro/ogadf-schema

**Comment by nbiederbeck** [comment]
Was this addressed with #63 ?

**Comment by HealthyPear** [comment]
Technically yes, but some checks are also in #65.

The reason is that there is no explicit function for this, we just import that library and use its methods in unit-tests.

**Comment by MaxNoe** [comment]
Yes, this was fixed in #63
