### ISSUE TITLE
astropy currently does not support writing fits columns with 1D arrays with only a single element

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/pyirf#44]
This is needed for writing point-like IRFs with only a single bin in the field of view offset.

Issue: https://github.com/astropy/astropy/issues/10765
Pull Request with fix: https://github.com/astropy/astropy/pull/10768

**Comment by MaxNoe** [comment]
This makes it impossible at the moment to strictly follow the GADF specification when there is only a single bin in field of view offset (or other quantities, but it probably only will be a problem for the FOV offset for point-like IRFs)

**Comment by MaxNoe** [comment]
Related issue in gammapy I opened: https://github.com/gammapy/gammapy/issues/3024

**Comment by HealthyPear** [comment]
This was fixed in astropy with https://github.com/astropy/astropy/pull/10768.

I think we can then close this issue no?

**Comment by maxnoe** [comment]
Astropy 4.0.2 is not yet published. Let's keep this open until it is and we require `astropy ~=4.0.2` in our `setup.py`

**Comment by maxnoe** [comment]
Solved in astropy 4.0.2 and 4.2 which are out since quite some time now.
