### ISSUE TITLE
histogram of simulated events(direction)

### ISSUE THREAD

**Issue by vuillaut** [cta-observatory/pyirf#51]
Compute the histogram of the events as a function of the position from any direction (useful: camera center or source) from the simulation info (view cone, etc...)

Needed for the full enclosure effective area.

**Comment by MaxNoe** [comment]
You need to integrate the PDF corsika uses, which should be the same as the one used for the zenith angle, so uniform in solid angle.

Formula here:
https://github.com/MaxNoe/phd_thesis/blob/a68b621cc8b658aa858342a4cfdaed68c3823257/thesis/chapters/appendix.tex#L135
