### ISSUE TITLE
Full-enclosure effective area

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/pyirf#53]
Description here: https://gamma-astro-data-formats.readthedocs.io/en/latest/irfs/full_enclosure/aeff/index.html

For this, #51 is a prerequisite

**Comment by HealthyPear** [comment]
@mstrzys has offered to work on this

**Comment by MaxNoe** [comment]
Implementation of the 2d effective area vs energy and fov offset in #68

**Comment by MaxNoe** [comment]
So what is now needed would be diffuse gamma data and a reference irf would be nice

**Comment by HealthyPear** [comment]
Technically we already have this, even though we need to test it (for which #54 is a requirement)

I will close this issue for the time being, we can open a new one if problems arise during the off-axis tests
