### ISSUE TITLE
Broken Links in Docs

### ISSUE THREAD

**Issue by nbiederbeck** [cta-observatory/pyirf#56]
The link to the notebook `comparison_with_EventDisplay.ipynb` in the *How to contribute / Benchmarks* section is broken.

Add this to #52 @MaxNoe ?

**Comment by MaxNoe** [comment]
yes, will do.

**Comment by MaxNoe** [comment]
ACtually, How to contribute / benchmarks no longer exists.

Can you run make clean html and check again?

**Comment by MaxNoe** [comment]
Fixed in #52
