### ISSUE TITLE
Argument order of `create_rad_max_hdu` inconsistent with the other functions

### ISSUE THREAD

**Issue by MaxNoe** [cta-observatory/pyirf#57]
Everywhere else, the actual thing to be stored is the first argument, here we give the binning first.

We should make this consistent

**Comment by HealthyPear** [comment]
Not sure I understand where the breaking change is: it is true that it is inconsistent with the other functions, but it's just a matter of this function definition right? If used as it is defined it returns the correct result.
Maybe I am confusing a breaking change with a bug?

**Comment by MaxNoe** [comment]
It just means that fixing this bug will be a breaking change to the API
