### ISSUE TITLE
Output IRF format

### ISSUE THREAD

**Issue by HealthyPear** [cta-observatory/pyirf#6]
**Introduction:**

This topic is still in an unofficial state and will likely evolve in time.
To check on the current its status, check the relevant sub-tasks of the IRF-WG [here](https://forge.in2p3.fr/projects/instrument-response-functions/wiki#Task-Assignment).

Feel free to add or link here any related issue / proposal / discussion.

**Current status:**

It is somewhat clear that we should follow the format described by the [Gamma Astro Data Format (GADF)](https://gamma-astro-data-formats.readthedocs.io/en/latest/).
We are following the latest development version.

**Comment by MaxNoe** [comment]
I think we should just make the decision, that we want to use OGADF and when we find it lacking something CTA requires, we will include it there.

After all, the intended purpose of OGADF is to become the CTA format and provide documentation of that format to the community.

**Comment by HealthyPear** [comment]
> I think we should just make the decision, that we want to use OGADF and when we find it lacking something CTA requires, we will include it there.
> 

This is indeed the current "decision" we took

**Comment by MaxNoe** [comment]
Ok, then let's close this for now and reopen if this needs discussion again.

**Comment by HealthyPear** [comment]
Well, I actually left it open for this purpose, since we will have soon people working on this...

**Comment by HealthyPear** [comment]
I mean this issue was not a bug or a one-time issue, it was meant as an open discussion to update along the development

**Comment by HealthyPear** [comment]
I would reopen it light of this

**Comment by MaxNoe** [comment]
I would rather see concrete issues as soon as something comes up.

E.g. an issue here when pyirf is violating some part of the standard or an issue at OGADF when something new is needed there. 

Having many open issues where we don't really expect any discussion is not a good idea as it will bury the issues that actually need work.

Especially with an eye on the coding sprint, we should aim at having concrete issues that contributors can start to tackle.

**Comment by MaxNoe** [comment]
Again, if there is currently nothing that needs discussion here, leave it closed. As soon as something comes up, reopen or open a new, more concrete issue.

But for now, the question has an answer.

**Comment by HealthyPear** [comment]
We should decide how to handle all auxiliary data (needed at least for diagnostics/testing) that can be produced together with the actual output file that we have to provide (basically the single FITS file containing the IRFs).

This data should be, e.g:
- the final selection cuts used to produce the IRFs (part of the provenance data of _pyirf_ - see #39)
- modified versions of some IRFs (e.g. collection areas with part of or no cuts applied)
- ...

**Comment by MaxNoe** [comment]
It is not against the GADF specification to have additional data in the FITS files, so we can include additional HDUs, e.g. for the gamma hadron cuts or multiplicity cuts (the theta cuts table is part of GADF, the RAD_MAX table) or benchmarks (angular resolution / energy bias and resolution). Though these can also be estimated from the IRFs themselves.

**Comment by HealthyPear** [comment]
Yes, the most important auxiliary information produced directly by _pyirf_ that we should add
- are the applied cuts that are not yet taken into account by the OGADF format (so g/h and multiplicity),
- IRFs with a different combination of cuts applied

Benchmarks are indeed not necessary, there are ready-to-use methods in e.g. _gammapy_ for plotting them given the respective IRF HDU.

**Comment by maxnoe** [comment]
Since these are not defined in the GADF standard, users right now can simply store the tables produced by pyirf in the output files using astropy table io. I think we can close this for now and open specific issues for missing functionality.
