### ISSUE TITLE
Downloadable internal data

### ISSUE THREAD

**Issue by GernotMaier** [cta-observatory/pyirf#73]
I suggest to remove this script - these data is not public and should not be accessible through a public download scripts.

https://github.com/cta-observatory/pyirf/blob/e406cbec07fbec53c4b9d8685cf7e8274632c973/download_test_data.sh#L3

(especially without any metadata / references). There is an ongoing discussion in CTAO/CTACon open data and I think we have to wait for the outcome before making any data accessible.

**Comment by HealthyPear** [comment]
I agree.
Though this will limit the ability of the IRF WG member to work I think....

@MaxNoe is it possible to temporarely set a password to your server that we can share via the aswg mailing list?

**Comment by MaxNoe** [comment]
Yes, no problem, I can password protect it and use travis' credential usage

**Comment by GernotMaier** [comment]
Great, thanks! Close this issue as soon as you have added the pw.

**Comment by MaxNoe** [comment]
Data is password protected now. Ask in the slack to get it.
